import localFont from 'next/font/local';
import './globals.css';
import Header from '@/app/_components/ui/Header';
import { verifySession } from './lib/session';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await verifySession();
  return (
    <html lang='en'>
      <body
        className={`flex h-svh flex-col items-center dark:bg-zinc-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header session={session} />
        {children}
      </body>
    </html>
  );
}
